### ISSUE TITLE
Papermill import breaks fastparquet writer

### ISSUE THREAD

**Issue by bartaelterman** [nteract/papermill#304] opened 2019-02-05 15:41 UTC
Hi,

I am experiencing issues with writing data to parquet (with dask and fastparquet) when I import papermill in my notebook. The issue is the result of the combination of a couple of packages so I'll be cross posting this issue on the different repositories.
- [fastparquet](https://github.com/dask/fastparquet/issues/398)
- papermill
- [dask-adlfs](https://github.com/eriklangenborg-rs/dask-adlfs) (unfortunately this repo has no issues)

Here is a code sample to reproduce the issue:

```
from random import randint
import papermill as pm
import pandas as pd
import dask.dataframe as dd

# a function to generate a sizeable dataframe
def get_large_df(cols, rows):
    data = {}
    for c in range(cols):
        data['rand{}'.format(c)] = [randint(0, 1000000) for x in range(rows)]
    return pd.DataFrame(data=data)

# Write the data frame to Azure Data Lake
df = get_large_df(10, 1_000)
ddf = dd.from_pandas(df, npartitions=4)
ddf.reset_index()
ddf.to_parquet('adl://my_container/test_parquet', engine='fastparquet', storage_options=STORAGE_OPTIONS)

# Read the data frame
dd.read_parquet('adl://prodstate/mh-webops/mh-webops/test/btan03/test_parquet', engine='fastparquet', storage_options=STORAGE_OPTIONS)
```

Reading the dataframe fails with the following exception:

```
Exception FileNotFoundError('test_parquet/_metadata/_metadata',)
```

It is unclear to me why dask looks for a `_metadata/_metadata` file because that does not exist. Now here is the funny thing:

- Simply removing the `import papermill as pm` resolves the issue,
- Writing to a local file instead of one on Azure works as expected,
- Writing and reading with `pyarrow` works (although I have to set `partition_on` when writing, which I didn't expect)

It is unclear to me which one of the packages is not playing nice.

**Comment by MSeal** [comment] 2019-02-18 01:25
@bartaelterman I cannot reproduce the issue on my machine. I got your script running with a fresh data lake store without issue. From reading the source code of papermill, the dask extension and a little of azure's packages I see no reason any additional package import would affect execution here. I do see a `_metadata` file being generated but not any `_metadata/_metadata` files. Have you retried with a fresh virtenv and latest packages? Is the target you're reading having a damaged metadata store perhaps (an additional import wouldn't affect this though).

**Comment by MSeal** [comment] 2019-03-02 17:01
Going to close this issue. I wasn't able to reproduce and this is likely a system or version issue on the machine seeing the problem.

**Closed by MSeal** 2019-03-02 17:01 UTC
