### ISSUE TITLE
Does papermill inject ids into the notebook

### ISSUE THREAD

**Issue by zyxue** [nteract/papermill#569] opened 2021-01-19 21:28 UTC
Although the notebook seems to run, I'm seeing a lot of error likes such when running papermill. 

```
Executing: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 36/36 [00:06<00:00,  5.32cell/s]
ERROR:traitlets:Notebook JSON is invalid: Additional properties are not allowed ('id' was unexpected)

Failed validating 'additionalProperties' in code_cell:

On instance['cells'][5]:
{'cell_type': 'code',
 'execution_count': 5,
 'id': 'spatial-newman',
 'metadata': {'execution': {'iopub.execute_input': '2021-01-19T19:30:42.089697Z',
                            'iopub.status.busy': '2021-01-19T19:30:42.089168Z',
                            'iopub.status.idle': '2021-01-19T19:30:42.090964Z',
                            'shell.execute_reply': '2021-01-19T19:30:42.091386Z'},
              'papermill': {'duration': 0.010499,
                            'end_time': '2021-01-19T19:30:42.091553',
                            'exception': False,
                            'start_time': '2021-01-19T19:30:42.081054',
                            'status': 'completed'},
              'tags': ['injected-parameters']},
 'outputs': ['...0 outputs...'],
 'source': '# Parameters\n'
...
```

My understanding is that it's complaining about lines like

```
 'id': 'spatial-newman',
```

but I'm not totally sure where is the id from. Also, different runs seem to have different ids (e.g. ` 'id': 'ethical-copyright'`)

Any idea on how to fix the error, please?

**Comment by MSeal** [comment] 2021-01-19 21:40
Thanks for reporting. This looks like a duplicate of https://github.com/nteract/papermill/issues/568

**Comment by zyxue** [comment] 2021-01-19 23:07
yes, close as a duplicate of #568

**Closed** 2021-01-19 23:07 UTC
