### ISSUE TITLE
Enhance the progress bar to display customizable message

### ISSUE THREAD

**Issue by 2008sliu** [nteract/papermill#734] opened 2023-11-01 00:58 UTC
## 🚀 Feature
- current status: When `process_bar` is True, tqdm progress bar is displayed with `desc="Executing"`
- suggested improvements: allow custimizing the message to be some task name

### Motivation

When `execute_notebook` is called in a process pool, many progress bars will be displayed and it is not possible to distinguish which one corresponds to which task.

## Possible implement without introducing new parameters
We can just allow the parameter of `execute_notebook` to be string. If it is non empty string, then display this string before the `Executing`

```
if progress_bar:
    from tqdm.auto import tqdm
    desc = 'Executing
    if isinstance(progress_basr, str):
        desc = progress_bar + '|' + desc
    self.pbar = tqdm(total=len(self.nb.cells), unit="cell", desc=desc)
```

**Comment by MSeal** [comment] 2024-02-08 22:45
Apologies for the late reply here. End of 2023 was very busy and I wasn't giving papermill much attention.

I believe this [PR#778](https://github.com/nteract/papermill/pull/778) that just merged solves this now and should enable custom description fields. Please reopen if something there isn't working as intended.

**Closed by MSeal** 2024-02-08 22:45 UTC
Labels: enhancement, help wanted
