### ISSUE TITLE
nbconvert 5.6.0 added an argument to run_cell which breaks papermill<=0.19.1

### ISSUE THREAD

**Issue by dan-hipschman-od** [nteract/papermill#410] opened 2019-08-09 22:48 UTC
Hi!

nbconvert 5.6.0 added a `store_history` argument to `run_cell`: https://github.com/jupyter/nbconvert/commit/40989d859da65bb3e3a3c588e5eeb2ff6cfc9cd1#diff-4692660441289779e28a3441f47a8bb0

In papermill 0.19.1, [`PapermillExecutePreprocessor.run_cell`](https://github.com/nteract/papermill/blob/0.19.1/papermill/preprocess.py#L98) doesn't have this argument, so when it's called by nbconvert, an exception is raised (this output is from papermill 0.18.2, but it looks like the problem is in 0.19.1 as well):
```
File "/opt/miniconda/lib/python3.6/site-packages/papermill/preprocess.py", line 27, in preprocess
nb, resources = self.papermill_process(nb_man, resources)
File "/opt/miniconda/lib/python3.6/site-packages/papermill/preprocess.py", line 76, in papermill_process
nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
File "/opt/miniconda/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 438, in preprocess_cell
reply, outputs = self.run_cell(cell, cell_index, store_history)
TypeError: run_cell() takes from 2 to 3 positional arguments but 4 were given
```

It looks like in papermill 1.0, `PapermillExecutePreprocessor` has changed so this isn't an issue there.

I solved the problem for myself by pegging the nbconvert version at 5.5.0. Not sure if that's suitable as a general fix for papermill <1.0. It also seems simple to just add `store_history` as a keyword arg to `run_cell`, as that should be backwards compatible with nbconvert 5.5.

Thanks!

**Comment by MSeal** [comment] 2019-08-11 04:54
We're unlikely to support the old versions of papermill + nbconvert in pairing. It creates too much friction in being able to move interfaces forward. Pinning nbconvert (and likely jupyter_client) back to versions available when 0.19.1 was release is the right choice if you're staying on < 1.0. This trend is also likely to continue with a later papermillrelease when nbconvert 6.0 extracts the execute preprocessor to another library.

**Comment by vizhur** [comment] 2019-08-12 14:52
@MSeal I can repro the issue with nbconvert 5.6.0 and pm 1.0.1. maybe a patch for pm to pin nbconvert upperbound would be a good mitigation?

**Comment by MSeal** [comment] 2019-08-12 16:26
Having trouble reproducing:

**Comment by MSeal** [comment] 2019-08-12 16:29
Having trouble reproducing in > 1.0.0:

```
09:04:34 mseal (master) ~/Workspace/papermill (venv:.py3local)  
$ papermill papermill/tests/notebooks/simple_execute.ipynb /tmp/out.ipynb
Input Notebook:  papermill/tests/notebooks/simple_execute.ipynb
Output Notebook: /tmp/out.ipynb
Executing: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.32cell/s]
09:05:10 mseal (master) ~/Workspace/papermill (venv:.py3local)  
$ pip freeze | grep nbconvert
nbconvert==5.6.0
$ pip freeze | grep papermill
papermill==1.0.1
```

This should only affect < 1.0 since run_cell calls aren't referenced therein. Perhaps you were running a different version of papermill than you thought? Or maybe it was a different stack trace?

**Comment by vizhur** [comment] 2019-08-12 16:43
my bad, 1.0.1 is fine with 5.6.0

**Comment by MSeal** [comment] 2019-09-10 16:22
Closing this issue as it seems documented and doesn't require any further action.

**Closed by MSeal** 2019-09-10 16:22 UTC
